routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->prefix('admin')->namespace('Admin')->group(function(){
    Route::resource('funcionarios','FuncionariosController');
    Route::resource('setores','SetoresController');
    Route::resource('cargos','CargosController');
});

app/Funcionario.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Funcionario extends Model
{
    protected $fillable = ['nome', 'email', 'idSetor', 'idCargo'];
}

app/Http/Controllers/Admin/FuncionariosController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Funcionario;
use App\Setor;

class FuncionariosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $listaPaginas = json_encode([
            ["titulo"=>"Home", "url"=>route('home')],
            ["titulo"=>"Funcionarios Cadastrados","url"=>""]
        ]);

        $listaFuncionarios = json_encode(Funcionario::select('id','nome','email', 'idSetor', 'idCargo')->get());
        $listaSetores = json_encode(Setor::select('id','nome')->get());

        return view('admin.funcionarios.index',compact('listaPaginas','listaFuncionarios','listaSetores'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        Funcionario::create($data); 
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        Funcionario::find($id)->update($data); 
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Funcionario::find($id)->delete(); 
        return redirect()->back();
    }
}

resources/views/admin/funcionarios/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">

            <painel titulo="Funcionarios Cadastrados">
                <navegacao v-bind:lista="{{$listaPaginas}}"></navegacao>
                <tabela-lista 
                    v-bind:titulos="['Id','Nome','Email','Setor', 'Cargo', 'Ações']"
                    v-bind:itens="{{$listaFuncionarios}}"
                    v-bind:setores="{{$listaSetores}}"
                    criar="#criar"
                    detalhe="/admin/funcionarios/"
                    editar="/admin/funcionarios/"
                    excluir="/admin/funcionarios/"
                    token="{{ csrf_token() }}"
                    modal="Sim"
                ></tabela-lista>
            </painel>
            

            <modal nome="criar">
                <painel titulo="Cadastrar Funcionario">
                    <formulario css="" action="{{route('funcionarios.store')}}" method="post" enctype="" token="{{ csrf_token() }}">
                        <div class="form-group">
                            <label for="txtNome">Nome</label>
                            <input type="text" class="form-control" id="nome" name="nome">
                        </div>
                        <div class="form-group">
                            <label for="txtNome">Email</label>
                            <input type="email" class="form-control" id="email" name="email">
                        </div>
                        <div class="form-group">
                            <label for="txtNmStatus">Setor</label>
                            <select name="idSetor" id="idSetor" class="form-control">
                                <option value="">Selecione</option>
                                <option value="1">TI</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="txtNmStatus">Cargo</label>
                            <select name="idCargo" id="idCargo" class="form-control">
                                <option value="">Selecione</option>
                                <option value="1">Administrador de Redes</option>
                                <option value="2">Service Desk</option>
                            </select>
                        </div>
                        <button class="btn btn-primary">Salvar</button>
                    </formulario>
                </painel>
            </modal>

            <modal nome="editar">
                <painel titulo="Editar Funcionario">
                    <formulario css="" v-bind:action="'/admin/funcionarios/' + $store.state.item.id" method="put" enctype="" token="{{ csrf_token() }}">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Nome</label>
                            <input type="text" class="form-control" id="nmSetor" name="nmSetor" v-model="$store.state.item.nome">
                        </div>
                        <div class="form-group">
                            <label for="txtNome">Email</label>
                            <input type="email" class="form-control" id="email" name="email" v-model="$store.state.item.email">
                        </div>
                        <div class="form-group">
                            <label for="txtNmStatus">Setor</label>
                            <select name="idSetor" id="idSetor" class="form-control"  v-model="$store.state.item.idSetor"> 
                                <option value="">Selecione</option>
                                <option value="1">TI</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="txtNmStatus">Cargo</label>
                            <select name="idCargo" id="idCargo" class="form-control"  v-model="$store.state.item.idCargo">
                                <option value="">Selecione</option>
                                <option value="1">Administrador de Redes</option>
                                <option value="2">Service Desk</option>
                            </select>
                        </div>
                        <button class="btn btn-primary">Atualizar</button>
                    </formulario>
                </painel>
            </modal>

            <modal nome="excluir">
                <painel titulo="Excluir Setor">
                    <formulario css="" v-bind:action="'/admin/setores/' + $store.state.item.id" method="put" enctype="" token="{{ csrf_token() }}">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Nome Setor</label>
                            <input type="text" class="form-control" id="nmSetor" name="nmSetor" v-model="$store.state.item.nome">
                        </div>
                        <div class="form-group">
                            <label for="txtNmStatus">Status</label>
                            <select name="status" id="status" class="form-control">
                                <option value="">Selecione</option>
                                <option value="1">Ativo</option>
                                <option value="0">Inativo</option>
                            </select>
                        </div>
                        <button class="btn btn-primary">Atualizar</button>
                    </formulario>
                </painel>
            </modal>

        </div>
    </div>
</div>
@endsection