routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->prefix('admin')->namespace('Admin')->group(function(){
    Route::resource('funcionarios','FuncionariosController');
    Route::resource('setores','SetoresController');
    Route::resource('cargos','CargosController');
});

app/Http/Controllers/Admin/SetoresController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Setor;

class SetoresController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $listaPaginas = json_encode([
            ["titulo"=>"Home", "url"=>route('home')],
            ["titulo"=>"Setores Cadastrados","url"=>""]
        ]);

        $listaSetores = json_encode(Setor::select('id','nome','status')->get());

        return view('admin.setores.index',compact('listaPaginas','listaSetores'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //dd($request->all());

        $data = $request->all();
        Setor::create($data); 
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        Setor::find($id)->update($data); 
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Setor::find($id)->delete(); 
        return redirect()->back();
    }
}

resources/views/admin/setores/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <painel titulo="Setores Cadastrados">
                <navegacao v-bind:lista="{{$listaPaginas}}"></navegacao>
                <tabela-lista 
                    v-bind:titulos="['Id','Titulo','Status','Ações']"
                    v-bind:itens="{{$listaSetores}}"
                    criar="#criar"
                    detalhe="/admin/setores/"
                    editar="/admin/setores/"
                    excluir="/admin/setores/"
                    token="{{ csrf_token() }}"
                    modal="Sim"
                ></tabela-lista>
            </painel>

            <modal nome="criar">
                <painel titulo="Cadastrar Setor">
                    <formulario css="" action="{{route('setores.store')}}" method="post" enctype="" token="{{ csrf_token() }}">
                        <div class="form-group">
                            <label for="txtNmSetor">Nome Setor</label>
                            <input type="text" class="form-control" id="nome" name="nome">
                        </div>
                        <div class="form-group">
                            <label for="txtNmStatus">Status</label>
                            <select name="status" id="status" class="form-control">
                                <option value="">Selecione</option>
                                <option value="1">Ativo</option>
                                <option value="0">Inativo</option>
                            </select>
                        </div>
                        <button class="btn btn-primary">Salvar</button>
                    </formulario>
                </painel>
            </modal>

            <modal nome="editar">
                <painel titulo="Editar Setor">
                    <formulario css="" v-bind:action="'/admin/setores/' + $store.state.item.id" method="put" enctype="" token="{{ csrf_token() }}">
                        <div class="form-group">
                            <label for="exampleInputEmail1">Nome Setor</label>
                            <input type="text" class="form-control" id="nmSetor" name="nmSetor" v-model="$store.state.item.nome">
                        </div>
                        <div class="form-group">
                            <label for="txtNmStatus">Status</label>
                            <select name="status" id="status" class="form-control" v-model="$store.state.item.status">
                                <option value="">Selecione</option>
                                <option value="1">Ativo</option>
                                <option value="0">Inativo</option>
                            </select>
                        </div>
                        <button class="btn btn-primary">Atualizar</button>
                    </formulario>
                </painel>
            </modal>


        </div>
    </div>
</div>
@endsection